# -*- coding: utf-8 -*-

SFDC_COUNTRIES = {
    "af": "Afghanistan",
    "ax": "Aland Islands",
    "al": "Albania",
    "dz": "Algeria",
    "as": "American Samoa",
    "ad": "Andorra",
    "ao": "Angola",
    "ai": "Anguilla",
    "aq": "Antarctica",
    "ag": "Antigua and Barbuda",
    "ar": "Argentina",
    "am": "Armenia",
    "aw": "Aruba",
    "au": "Australia",
    "at": "Austria",
    "az": "Azerbaijan",
    "bs": "Bahamas",
    "bh": "Bahrain",
    "bd": "Bangladesh",
    "bb": "Barbados",
    "by": "Belarus",
    "be": "Belgium",
    "bz": "Belize",
    "bj": "Benin",
    "bm": "Bermuda",
    "bt": "Bhutan",
    "bo": "Bolivia, Plurinational State of",
    "bq": "Bonaire, Sint Eustatius and Saba",
    "ba": "Bosnia and Herzegovina",
    "bw": "Botswana",
    "bv": "Bouvet Island",
    "br": "Brazil",
    "io": "British Indian Ocean Territory",
    "bn": "Brunei Darussalam",
    "bg": "Bulgaria",
    "bf": "Burkina Faso",
    "bi": "Burundi",
    "kh": "Cambodia",
    "cm": "Cameroon",
    "ca": "Canada",
    "cv": "Cape Verde",
    "ky": "Cayman Islands",
    "cf": "Central African Republic",
    "td": "Chad",
    "cl": "Chile",
    "cn": "China",
    "cx": "Christmas Island",
    "cc": "Cocos (Keeling) Islands",
    "co": "Colombia",
    "km": "Comoros",
    "cg": "Congo",
    "cd": "Congo, the Democratic Republic of the",
    "ck": "Cook Islands",
    "cr": "Costa Rica",
    "ci": "Cote d'Ivoire",
    "hr": "Croatia",
    "cu": "Cuba",
    "cw": "Curaçao",
    "cy": "Cyprus",
    "cz": "Czech Republic",
    "dk": "Denmark",
    "dj": "Djibouti",
    "dm": "Dominica",
    "do": "Dominican Republic",
    "ec": "Ecuador",
    "eg": "Egypt",
    "sv": "El Salvador",
    "gq": "Equatorial Guinea",
    "er": "Eritrea",
    "ee": "Estonia",
    "et": "Ethiopia",
    "fk": "Falkland Islands (Malvinas)",
    "fo": "Faroe Islands",
    "fj": "Fiji",
    "fi": "Finland",
    "fr": "France",
    "gf": "French Guiana",
    "pf": "French Polynesia",
    "tf": "French Southern Territories",
    "ga": "Gabon",
    "gm": "Gambia",
    "ge": "Georgia",
    "de": "Germany",
    "gh": "Ghana",
    "gi": "Gibraltar",
    "gr": "Greece",
    "gl": "Greenland",
    "gd": "Grenada",
    "gp": "Guadeloupe",
    "gu": "Guam",
    "gt": "Guatemala",
    "gg": "Guernsey",
    "gn": "Guinea",
    "gw": "Guinea-Bissau",
    "gy": "Guyana",
    "ht": "Haiti",
    "hm": "Heard Island and McDonald Islands",
    "va": "Holy See (Vatican City State)",
    "hn": "Honduras",
    "hk": "Hong Kong",
    "hu": "Hungary",
    "is": "Iceland",
    "in": "India",
    "id": "Indonesia",
    "ir": "Iran, Islamic Republic of",
    "iq": "Iraq",
    "ie": "Ireland",
    "im": "Isle of Man",
    "il": "Israel",
    "it": "Italy",
    "jm": "Jamaica",
    "jp": "Japan",
    "je": "Jersey",
    "jo": "Jordan",
    "kz": "Kazakhstan",
    "ke": "Kenya",
    "ki": "Kiribati",
    "kp": "Korea, Democratic People's Republic of",
    "kr": "Korea, Republic of",
    "kw": "Kuwait",
    "kg": "Kyrgyzstan",
    "la": "Lao People's Democratic Republic",
    "lv": "Latvia",
    "lb": "Lebanon",
    "ls": "Lesotho",
    "lr": "Liberia",
    "ly": "Libya",
    "li": "Liechtenstein",
    "lt": "Lithuania",
    "lu": "Luxembourg",
    "mo": "Macao",
    "mk": "Macedonia, the former Yugoslav Republic of",
    "mg": "Madagascar",
    "mw": "Malawi",
    "my": "Malaysia",
    "mv": "Maldives",
    "ml": "Mali",
    "mt": "Malta",
    "mh": "Marshall Islands",
    "mq": "Martinique",
    "mr": "Mauritania",
    "mu": "Mauritius",
    "yt": "Mayotte",
    "mx": "Mexico",
    "fm": "Micronesia",
    "md": "Moldova, Republic of",
    "mc": "Monaco",
    "mn": "Mongolia",
    "me": "Montenegro",
    "ms": "Montserrat",
    "ma": "Morocco",
    "mz": "Mozambique",
    "mm": "Myanmar",
    "na": "Namibia",
    "nr": "Nauru",
    "np": "Nepal",
    "nl": "Netherlands",
    "an": "Netherlands Antilles",
    "nc": "New Caledonia",
    "nz": "New Zealand",
    "ni": "Nicaragua",
    "ne": "Niger",
    "ng": "Nigeria",
    "nu": "Niue",
    "nf": "Norfolk Island",
    "mp": "Northern Mariana Islands",
    "no": "Norway",
    "om": "Oman",
    "pk": "Pakistan",
    "pw": "Palau",
    "ps": "Palestine",
    "pa": "Panama",
    "pg": "Papua New Guinea",
    "py": "Paraguay",
    "pe": "Peru",
    "ph": "Philippines",
    "pn": "Pitcairn",
    "pl": "Poland",
    "pt": "Portugal",
    "pr": "Puerto Rico",
    "qa": "Qatar",
    "re": "Reunion",
    "ro": "Romania",
    "ru": "Russian Federation",
    "rw": "Rwanda",
    "bl": "Saint Barthélemy",
    "sh": "Saint Helena, Ascension and Tristan da Cunha",
    "kn": "Saint Kitts and Nevis",
    "lc": "Saint Lucia",
    "mf": "Saint Martin (French part)",
    "pm": "Saint Pierre and Miquelon",
    "vc": "Saint Vincent and the Grenadines",
    "ws": "Samoa",
    "sm": "San Marino",
    "st": "Sao Tome and Principe",
    "sa": "Saudi Arabia",
    "sn": "Senegal",
    "rs": "Serbia",
    "sc": "Seychelles",
    "sl": "Sierra Leone",
    "sg": "Singapore",
    "sx": "Sint Maarten (Dutch part)",
    "sk": "Slovakia",
    "si": "Slovenia",
    "sb": "Solomon Islands",
    "so": "Somalia",
    "za": "South Africa",
    "gs": "South Georgia and the South Sandwich Islands",
    "ss": "South Sudan",
    "es": "Spain",
    "lk": "Sri Lanka",
    "sd": "Sudan",
    "sr": "Suriname",
    "sj": "Svalbard and Jan Mayen",
    "sz": "Swaziland",
    "se": "Sweden",
    "ch": "Switzerland",
    "sy": "Syrian Arab Republic",
    "tw": "Taiwan",
    "tj": "Tajikistan",
    "tz": "Tanzania, United Republic of",
    "th": "Thailand",
    "tl": "Timor-Leste",
    "tg": "Togo",
    "tk": "Tokelau",
    "to": "Tonga",
    "tt": "Trinidad and Tobago",
    "tn": "Tunisia",
    "tr": "Turkey",
    "tm": "Turkmenistan",
    "tc": "Turks and Caicos Islands",
    "tv": "Tuvalu",
    "vi": "U.S. Virgin Islands",
    "ug": "Uganda",
    "ua": "Ukraine",
    "ae": "United Arab Emirates",
    "gb": "United Kingdom",
    "us": "United States",
    "um": "United States Minor Outlying Islands",
    "uy": "Uruguay",
    "uz": "Uzbekistan",
    "vu": "Vanuatu",
    "ve": "Venezuela, Bolivarian Republic of",
    "vn": "Viet Nam",
    "vg": "Virgin Islands, British",
    "wf": "Wallis and Futuna",
    "eh": "Western Sahara",
    "ye": "Yemen",
    "zm": "Zambia",
    "zw": "Zimbabwe",
}
SFDC_COUNTRIES_LIST = list(SFDC_COUNTRIES.keys())
COUNTRY_CODES_MAP = {
    "afg": "af",
    "ala": "ax",
    "alb": "al",
    "dza": "dz",
    "asm": "as",
    "and": "ad",
    "ago": "ao",
    "aia": "ai",
    "ata": "aq",
    "atg": "ag",
    "arg": "ar",
    "arm": "am",
    "abw": "aw",
    "aus": "au",
    "aut": "at",
    "aze": "az",
    "bhs": "bs",
    "bhr": "bh",
    "bgd": "bd",
    "brb": "bb",
    "blr": "by",
    "bel": "be",
    "blz": "bz",
    "ben": "bj",
    "bmu": "bm",
    "btn": "bt",
    "bol": "bo",
    "bih": "ba",
    "bwa": "bw",
    "bvt": "bv",
    "bra": "br",
    "vgb": "vg",
    "iot": "io",
    "brn": "bn",
    "bgr": "bg",
    "bfa": "bf",
    "bdi": "bi",
    "khm": "kh",
    "cmr": "cm",
    "can": "ca",
    "cpv": "cv",
    "cym": "ky",
    "caf": "cf",
    "tcd": "td",
    "chl": "cl",
    "chn": "cn",
    "hkg": "hk",
    "mac": "mo",
    "cxr": "cx",
    "cck": "cc",
    "col": "co",
    "com": "km",
    "cog": "cg",
    "cod": "cd",
    "cok": "ck",
    "cri": "cr",
    "civ": "ci",
    "hrv": "hr",
    "cub": "cu",
    "cyp": "cy",
    "cze": "cz",
    "dnk": "dk",
    "dji": "dj",
    "dma": "dm",
    "dom": "do",
    "ecu": "ec",
    "egy": "eg",
    "slv": "sv",
    "gnq": "gq",
    "eri": "er",
    "est": "ee",
    "eth": "et",
    "flk": "fk",
    "fro": "fo",
    "fji": "fj",
    "fin": "fi",
    "fra": "fr",
    "guf": "gf",
    "pyf": "pf",
    "atf": "tf",
    "gab": "ga",
    "gmb": "gm",
    "geo": "ge",
    "deu": "de",
    "gha": "gh",
    "gib": "gi",
    "grc": "gr",
    "grl": "gl",
    "grd": "gd",
    "glp": "gp",
    "gum": "gu",
    "gtm": "gt",
    "ggy": "gg",
    "gin": "gn",
    "gnb": "gw",
    "guy": "gy",
    "hti": "ht",
    "hmd": "hm",
    "vat": "va",
    "hnd": "hn",
    "hun": "hu",
    "isl": "is",
    "ind": "in",
    "idn": "id",
    "irn": "ir",
    "irq": "iq",
    "irl": "ie",
    "imn": "im",
    "isr": "il",
    "ita": "it",
    "jam": "jm",
    "jpn": "jp",
    "jey": "je",
    "jor": "jo",
    "kaz": "kz",
    "ken": "ke",
    "kir": "ki",
    "prk": "kp",
    "kor": "kr",
    "kwt": "kw",
    "kgz": "kg",
    "lao": "la",
    "lva": "lv",
    "lbn": "lb",
    "lso": "ls",
    "lbr": "lr",
    "lby": "ly",
    "lie": "li",
    "ltu": "lt",
    "lux": "lu",
    "mkd": "mk",
    "mdg": "mg",
    "mwi": "mw",
    "mys": "my",
    "mdv": "mv",
    "mli": "ml",
    "mlt": "mt",
    "mhl": "mh",
    "mtq": "mq",
    "mrt": "mr",
    "mus": "mu",
    "myt": "yt",
    "mex": "mx",
    "fsm": "fm",
    "mda": "md",
    "mco": "mc",
    "mng": "mn",
    "mne": "me",
    "msr": "ms",
    "mar": "ma",
    "moz": "mz",
    "mmr": "mm",
    "nam": "na",
    "nru": "nr",
    "npl": "np",
    "nld": "nl",
    "ant": "an",
    "ncl": "nc",
    "nzl": "nz",
    "nic": "ni",
    "ner": "ne",
    "nga": "ng",
    "niu": "nu",
    "nfk": "nf",
    "mnp": "mp",
    "nor": "no",
    "omn": "om",
    "pak": "pk",
    "plw": "pw",
    "pse": "ps",
    "pan": "pa",
    "png": "pg",
    "pry": "py",
    "per": "pe",
    "phl": "ph",
    "pcn": "pn",
    "pol": "pl",
    "prt": "pt",
    "pri": "pr",
    "qat": "qa",
    "reu": "re",
    "rou": "ro",
    "rus": "ru",
    "rwa": "rw",
    "blm": "bl",
    "shn": "sh",
    "kna": "kn",
    "lca": "lc",
    "maf": "mf",
    "spm": "pm",
    "vct": "vc",
    "wsm": "ws",
    "smr": "sm",
    "stp": "st",
    "sau": "sa",
    "sen": "sn",
    "srb": "rs",
    "syc": "sc",
    "sle": "sl",
    "sgp": "sg",
    "svk": "sk",
    "svn": "si",
    "slb": "sb",
    "som": "so",
    "zaf": "za",
    "sgs": "gs",
    "ssd": "ss",
    "esp": "es",
    "lka": "lk",
    "sdn": "sd",
    "sur": "sr",
    "sjm": "sj",
    "swz": "sz",
    "swe": "se",
    "che": "ch",
    "syr": "sy",
    "twn": "tw",
    "tjk": "tj",
    "tza": "tz",
    "tha": "th",
    "tls": "tl",
    "tgo": "tg",
    "tkl": "tk",
    "ton": "to",
    "tto": "tt",
    "tun": "tn",
    "tur": "tr",
    "tkm": "tm",
    "tca": "tc",
    "tuv": "tv",
    "uga": "ug",
    "ukr": "ua",
    "are": "ae",
    "gbr": "gb",
    "usa": "us",
    "umi": "um",
    "ury": "uy",
    "uzb": "uz",
    "vut": "vu",
    "ven": "ve",
    "vnm": "vn",
    "vir": "vi",
    "wlf": "wf",
    "esh": "eh",
    "yem": "ye",
    "zmb": "zm",
    "zwe": "zw",
}


def convert_country_3_to_2(ccode):
    ccode = ccode.lower()
    return COUNTRY_CODES_MAP.get(ccode, None)
