# Generated by Django 3.2.22 on 2023-11-01 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("title", models.CharField(max_length=255)),
                ("affiliation", models.CharField(max_length=255)),
                ("verified_general", models.BooleanField(default=False, help_text="General spot-check verification")),
                ("verified_linkedin", models.BooleanField(default=False, help_text="LinkedIn verification")),
                ("verified_research", models.BooleanField(default=False, help_text="Research verification")),
                ("approved", models.BooleanField(default=False)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.TextField(blank=True)),
                ("token", models.UUIDField()),
                ("email_confirmed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Petition",
                "verbose_name_plural": "Petitions",
                "db_table": "petition",
            },
        ),
    ]
