# Generated by Django 3.2.22 on 2023-11-07 00:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="petition",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="petition",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
