# Generated by Django 4.2.14 on 2024-08-28 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0003_petition_vip"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Petition",
        ),
    ]
