[tool.ruff]
line-length = 150
indent-width = 4
target-version = 'py312'
extend-exclude = ["docs"]

[tool.ruff.lint]
# Set what ruff should check for.
# See https://docs.astral.sh//ruff/rules/ for a list of rules.
select = [
  "A", # flake8-builtin errors
  "B", # bugbear errors
  "C4", # flake8-comprehensions errors
  "DJ", # flake8-django errors
  "E", # pycodestyle errors
  "F", # pyflakes errors
  "I", # import sorting
  "Q", # flake8-quotes errors
  "T20", # flake8-print errors
  "UP", # py-upgrade
  "W", # pycodestyle warnings
]

[tool.ruff.lint.per-file-ignores]
# T201: `print()` statements in management commands are allowed.
"basket/news/management/commands/*" = ["T201"]

[tool.ruff.lint.isort]
known-first-party = ["basket"]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]

[tool.ruff.lint.isort.sections]
django = ["django"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "basket.settings"
addopts = "-ra --ignore=vendor"
