[tool.black]
line-length = 150
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
select = [
  "A", # flake8-builtin errors.
  "B", # bugbear errors
  "DJ", # flake8-django errors.
  "E", # pycodestyle errors
  "F", # pyflakes errors
  "I", # import sorting
  "Q", # flake8-quotes errors
  "W", # pycodestyle warnings
]
line-length = 150  # To match black.
target-version = 'py39'
extend-exclude = ["__pycache__", "docker", "docs"]

[tool.ruff.per-file-ignores]
"bedrock/settings/__init__.py" = ["F405"]

[tool.ruff.isort]
known-first-party = ["basket"]
section-order = ["future", "standard-library", "django", "third-party", "first-party", "local-folder"]

[tool.ruff.isort.sections]
django = ["django"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "basket.settings"
addopts = "-ra --ignore=vendor"
