[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.ruff]
# Set what ruff should check for.
# See https://beta.ruff.rs/docs/rules/ for a list of rules.
select = [
    "A", # flake8-builtin errors.
    "B", # bugbear errors
    # "DJ", # flake8-django errors.
    "E", # pycodestyle errors
    "F", # pyflakes errors
    # TODO: Currently ruff doesn't have the ability to sort Django imports together.
    # "I", # import sorting
    "Q", # flake8-quotes errors
    "W", # pycodestyle warnings
]
line-length = 88  # To match black.
target-version = 'py39'
extend-exclude = ["__pycache__", "docker", "docs"]

[tool.ruff.per-file-ignores]
"bedrock/settings/__init__.py" = ["F405"]

[tool.isort]
combine_as_imports = true
default_section = 'THIRDPARTY'
include_trailing_comma = true
known_django = 'django'
known_first_party = 'basket'
profile = 'black'
sections = 'FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'

[tool.pytest.ini_options]
addopts = "-ra --ignore=vendor"
DJANGO_SETTINGS_MODULE = "basket.settings"
