# Generated by Django 5.2.17 on 2026-09-21 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormRoute",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("form_id", models.SlugField(help_text='e.g. "enterprise-contact"', unique=True)),
                ("name", models.CharField(help_text='e.g. "Enterprise Contact Form"', max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("created_by", models.CharField(help_text="Email, for audit trail", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormDestination",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("dest_type", models.CharField(choices=[("gsheet", "Google Sheet")], max_length=20)),
                ("label", models.CharField(max_length=255)),
                ("config", models.JSONField(help_text='gsheet: {"sheet_id": "...", "tab": "Responses"}')),
                ("field_map", models.JSONField(help_text='gsheet: {"email": "A", "first_name": "B"} -- CMS field to column letter')),
                ("active", models.BooleanField(default=True)),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="destinations", to="contact.formroute")),
            ],
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload", models.JSONField(help_text="Raw, unmodified CMS data")),
                ("source_url", models.URLField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "queued"), ("delivered", "delivered"), ("failed", "failed")], default="queued", max_length=20
                    ),
                ),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="submissions", to="contact.formroute")),
            ],
        ),
    ]
