# Generated by Django 5.2.17 on 2026-09-22 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formsubmission",
            name="source_url",
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
