# Generated by Django 5.2.17 on 2026-09-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_formsubmission_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdestination",
            name="field_map",
            field=models.JSONField(
                help_text=(
                    'gsheet: {"email": "Business Email", "first_name": "First Name"} -- CMS field to the '
                    "sheet's own header text (row 1), matched at delivery time -- not a fixed column "
                    "letter, so reordering columns or adding new ones later doesn't misalign "
                    "already-delivered rows."
                )
            ),
        ),
    ]
