# Generated by Django 5.2.17 on 2026-09-24 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_alter_formsubmission_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdestination",
            name="next_row",
            field=models.PositiveIntegerField(
                blank=True, help_text="Sheet row the next gsheet delivery will claim; managed automatically, do not edit.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="formdestination",
            name="field_map",
            field=models.JSONField(
                help_text=(
                    'gsheet: {"email": "Business Email", "first_name": "First Name"} -- CMS field to the '
                    "sheet's own header text (row 1), matched at delivery time -- not a fixed column "
                    "letter, so reordering columns or adding new ones later doesn't misalign "
                    "already-delivered rows."
                )
            ),
        ),
        migrations.CreateModel(
            name="FormDelivery",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "queued"), ("delivered", "delivered"), ("failed", "failed")], default="queued", max_length=20
                    ),
                ),
                ("row_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="contact.formdestination"),
                ),
                (
                    "submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="contact.formsubmission"),
                ),
            ],
            options={
                "unique_together": {("submission", "destination")},
            },
        ),
    ]
