# Generated by Django 5.2.17 on 2026-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_alter_formdestination_field_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdestination",
            name="next_row",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sheet row the next gsheet delivery will claim; managed automatically, do not edit.",
                null=True,
            ),
        ),
    ]
