# Generated by Django 5.2.17 on 2026-09-23 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_formdestination_next_row"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDeliveryClaim",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("row_number", models.PositiveIntegerField()),
                (
                    "destination",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_claims", to="contact.formdestination"),
                ),
                (
                    "submission",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="delivery_claims", to="contact.formsubmission"),
                ),
            ],
            options={
                "unique_together": {("submission", "destination")},
            },
        ),
    ]
