# Generated by Django 4.2.14 on 2024-08-01 19:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import basket.news.fields
import basket.news.models

# Notes:
# basket.news.migrations.0005_convert_newsletter_vendor_id
# - `convert_vendor_id` has already run on all data. Removing.
# basket.news.migrations.0010_auto_20160607_0815
# - `convert_transactionals` has already run on all data. Removing.
# basket.news.migrations.0014_move_sms_messages
# - `move_sms_messages` no longer needed. Removing.
# basket.news.migrations.0026_newsletter_is_waitlist
# - `set_waitlist_field` has already run on all data. Removing.


class Migration(migrations.Migration):
    replaces = [
        ("news", "0001_initial"),
        ("news", "0002_delete_subscriber"),
        ("news", "0003_auto_20151202_0808"),
        ("news", "0005_convert_newsletter_vendor_id"),
        ("news", "0004_queuedtask"),
        ("news", "0006_merge"),
        ("news", "0007_auto_20160531_1454"),
        ("news", "0008_auto_20160605_1345"),
        ("news", "0009_transactionalemailmessage"),
        ("news", "0010_auto_20160607_0815"),
        ("news", "0011_auto_20160607_1203"),
        ("news", "0012_auto_20170713_1021"),
        ("news", "0013_auto_20170907_1216"),
        ("news", "0014_move_sms_messages"),
        ("news", "0015_delete_smsmessage"),
        ("news", "0016_auto_20190515_1951"),
        ("news", "0017_auto_20190627_2116"),
        ("news", "0018_commonvoiceupdate"),
        ("news", "0019_acoustictxemailmessage"),
        ("news", "0020_auto_20210225_1544"),
        ("news", "0021_delete_localizedsmsmessage"),
        ("news", "0022_delete_transactionalemailmessage"),
        ("news", "0023_newsletter_firefox_confirm"),
        ("news", "0024_newsletter_is_mofo"),
        ("news", "0025_auto_20220308_1803"),
        ("news", "0026_newsletter_is_waitlist"),
        ("news", "0027_alter_newsletter_requires_double_optin"),
        ("news", "0028_django_jsonfield"),
        ("news", "0029_delete_commonvoiceupdate"),
        ("news", "0030_alter_localestewards_unique_together_and_more"),
        ("news", "0031_brazetxemailmessage"),
        ("news", "0032_delete_acoustictxemailmessage"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APIUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Descriptive name of this user", max_length=256)),
                ("api_key", models.CharField(db_index=True, default=basket.news.models.get_uuid, max_length=40)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "API User",
            },
        ),
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_domain", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FailedTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("when", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("task_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("exc", models.TextField(default=None, help_text="repr(exception)", null=True)),
                ("einfo", models.TextField(default=None, help_text="repr(einfo)", null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="The ID for the newsletter that will be used by clients", unique=True)),
                ("title", models.CharField(help_text="Public name of newsletter in English", max_length=128)),
                ("description", models.CharField(blank=True, help_text="One-line description of newsletter in English", max_length=256)),
                (
                    "show",
                    models.BooleanField(default=False, help_text="Whether to show this newsletter in lists of newsletters, even to non-subscribers"),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text=(
                            "Whether this newsletter is active. Inactive newsletters are only shown to those who are already subscribed, "
                            "and might have other differences in behavior."
                        ),
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this newsletter is private. Private newsletters require the subscribe requests to use an API key.",
                    ),
                ),
                (
                    "indent",
                    models.BooleanField(default=False, help_text="Whether this newsletter is indented in the email preference center."),
                ),
                ("vendor_id", models.CharField(help_text="The backend vendor's identifier for this newsletter", max_length=128)),
                ("languages", models.CharField(help_text="Comma-separated list of the language codes that this newsletter supports", max_length=200)),
                (
                    "requires_double_optin",
                    models.BooleanField(
                        default=False, help_text="True if subscribing to this newsletter requires someone to respond to a confirming email."
                    ),
                ),
                (
                    "firefox_confirm",
                    models.BooleanField(
                        default=False, help_text="Whether to send the Firefox or Mozilla branded confirmation message for this newsletter"
                    ),
                ),
                (
                    "is_mofo",
                    models.BooleanField(
                        default=False, help_text="True if subscribing to this newsletter should mark someone as relevant to the Mozilla Foundation"
                    ),
                ),
                (
                    "is_waitlist",
                    models.BooleanField(
                        default=False, help_text="True if the newsletter is a waiting list. A waitlist can have additional arbitrary fields."
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Order to display the newsletters on the web site. Newsletters with lower order numbers will display first.",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(help_text="The ID for the group that will be used by clients", unique=True)),
                ("title", models.CharField(help_text="Public name of group in English", max_length=128)),
                ("description", models.CharField(blank=True, help_text="One-line description of group in English", max_length=256)),
                (
                    "show",
                    models.BooleanField(
                        default=False, help_text="Whether to show this group in lists of newsletters and groups, even to non-subscribers"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=False, help_text="Whether this group should be considered when subscription requests are received."),
                ),
                ("newsletters", models.ManyToManyField(related_name="newsletter_groups", to="news.newsletter")),
            ],
        ),
        migrations.CreateModel(
            name="QueuedTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("when", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("name", models.CharField(max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="BrazeTxEmailMessage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("message_id", models.SlugField(help_text="The ID for the message that will be used by clients")),
                ("description", models.CharField(blank=True, help_text="Optional short description of this message", max_length=200)),
                (
                    "language",
                    basket.news.fields.LocaleField(
                        choices=[
                            ("ach", "ach (Acholi)"),
                            ("af", "af (Afrikaans)"),
                            ("ak", "ak (Akan)"),
                            ("am-et", "am-et (Amharic)"),
                            ("an", "an (Aragonese)"),
                            ("ar", "ar (Arabic)"),
                            ("as", "as (Assamese)"),
                            ("ast", "ast (Asturian)"),
                            ("az", "az (Azerbaijani)"),
                            ("azz", "azz (Highland Puebla Nahuatl)"),
                            ("be", "be (Belarusian)"),
                            ("bg", "bg (Bulgarian)"),
                            ("bm", "bm (Bambara)"),
                            ("bn", "bn (Bengali)"),
                            ("bn-BD", "bn-BD (Bengali (Bangladesh))"),
                            ("bn-IN", "bn-IN (Bengali (India))"),
                            ("bo", "bo (Tibetan)"),
                            ("br", "br (Breton)"),
                            ("brx", "brx (Bodo)"),
                            ("bs", "bs (Bosnian)"),
                            ("ca", "ca (Catalan)"),
                            ("ca-valencia", "ca-valencia (Catalan (Valencian))"),
                            ("cak", "cak (Kaqchikel)"),
                            ("ckb", "ckb (Central Kurdish)"),
                            ("crh", "crh (Crimean Tatar)"),
                            ("cs", "cs (Czech)"),
                            ("csb", "csb (Kashubian)"),
                            ("cy", "cy (Welsh)"),
                            ("da", "da (Danish)"),
                            ("dbg", "dbg (Debug Robot)"),
                            ("de", "de (German)"),
                            ("de-AT", "de-AT (German (Austria))"),
                            ("de-CH", "de-CH (German (Switzerland))"),
                            ("de-DE", "de-DE (German (Germany))"),
                            ("dsb", "dsb (Lower Sorbian)"),
                            ("ee", "ee (Ewe)"),
                            ("el", "el (Greek)"),
                            ("en-AU", "en-AU (English (Australian))"),
                            ("en-CA", "en-CA (English (Canadian))"),
                            ("en-GB", "en-GB (English (British))"),
                            ("en-NZ", "en-NZ (English (New Zealand))"),
                            ("en-US", "en-US (English (US))"),
                            ("en-ZA", "en-ZA (English (South African))"),
                            ("eo", "eo (Esperanto)"),
                            ("es", "es (Spanish)"),
                            ("es-AR", "es-AR (Spanish (Argentina))"),
                            ("es-CL", "es-CL (Spanish (Chile))"),
                            ("es-ES", "es-ES (Spanish (Spain))"),
                            ("es-MX", "es-MX (Spanish (Mexico))"),
                            ("et", "et (Estonian)"),
                            ("eu", "eu (Basque)"),
                            ("fa", "fa (Persian)"),
                            ("ff", "ff (Fulah)"),
                            ("fi", "fi (Finnish)"),
                            ("fj-FJ", "fj-FJ (Fijian)"),
                            ("fr", "fr (French)"),
                            ("fur-IT", "fur-IT (Friulian)"),
                            ("fy-NL", "fy-NL (Frisian)"),
                            ("ga", "ga (Irish)"),
                            ("ga-IE", "ga-IE (Irish)"),
                            ("gd", "gd (Gaelic (Scotland))"),
                            ("gl", "gl (Galician)"),
                            ("gn", "gn (Guarani)"),
                            ("gu", "gu (Gujarati)"),
                            ("gu-IN", "gu-IN (Gujarati (India))"),
                            ("ha", "ha (Hausa)"),
                            ("he", "he (Hebrew)"),
                            ("hi", "hi (Hindi)"),
                            ("hi-IN", "hi-IN (Hindi (India))"),
                            ("hr", "hr (Croatian)"),
                            ("hsb", "hsb (Upper Sorbian)"),
                            ("hu", "hu (Hungarian)"),
                            ("hy-AM", "hy-AM (Armenian)"),
                            ("hye", "hye (Armenian Eastern Classic Orthography)"),
                            ("ia", "ia (Interlingua)"),
                            ("id", "id (Indonesian)"),
                            ("ig", "ig (Igbo)"),
                            ("is", "is (Icelandic)"),
                            ("it", "it (Italian)"),
                            ("ja", "ja (Japanese)"),
                            ("ja-JP-mac", "ja-JP-mac (Japanese)"),
                            ("ka", "ka (Georgian)"),
                            ("kab", "kab (Kabyle)"),
                            ("kk", "kk (Kazakh)"),
                            ("km", "km (Khmer)"),
                            ("kn", "kn (Kannada)"),
                            ("ko", "ko (Korean)"),
                            ("kok", "kok (Konkani)"),
                            ("ks", "ks (Kashmiri)"),
                            ("ku", "ku (Kurdish)"),
                            ("la", "la (Latin)"),
                            ("lg", "lg (Luganda)"),
                            ("lij", "lij (Ligurian)"),
                            ("ln", "ln (Lingala)"),
                            ("lo", "lo (Lao)"),
                            ("lt", "lt (Lithuanian)"),
                            ("ltg", "ltg (Latgalian)"),
                            ("lv", "lv (Latvian)"),
                            ("mai", "mai (Maithili)"),
                            ("meh", "meh (Mixteco Yucuhiti)"),
                            ("mg", "mg (Malagasy)"),
                            ("mi", "mi (Maori (Aotearoa))"),
                            ("mk", "mk (Macedonian)"),
                            ("ml", "ml (Malayalam)"),
                            ("mn", "mn (Mongolian)"),
                            ("mr", "mr (Marathi)"),
                            ("ms", "ms (Malay)"),
                            ("my", "my (Burmese)"),
                            ("nb-NO", "nb-NO (Norwegian (Bokmål))"),
                            ("ne-NP", "ne-NP (Nepali)"),
                            ("nl", "nl (Dutch)"),
                            ("nn-NO", "nn-NO (Norwegian (Nynorsk))"),
                            ("nr", "nr (Ndebele, South)"),
                            ("nso", "nso (Northern Sotho)"),
                            ("oc", "oc (Occitan (Lengadocian))"),
                            ("or", "or (Odia)"),
                            ("pa", "pa (Punjabi)"),
                            ("pa-IN", "pa-IN (Punjabi (India))"),
                            ("pl", "pl (Polish)"),
                            ("pt-BR", "pt-BR (Portuguese (Brazilian))"),
                            ("pt-PT", "pt-PT (Portuguese (Portugal))"),
                            ("rm", "rm (Romansh)"),
                            ("ro", "ro (Romanian)"),
                            ("ru", "ru (Russian)"),
                            ("rw", "rw (Kinyarwanda)"),
                            ("sa", "sa (Sanskrit)"),
                            ("sah", "sah (Sakha)"),
                            ("sat", "sat (Santali)"),
                            ("sc", "sc (Sardinian)"),
                            ("scn", "scn (Sicilian)"),
                            ("sco", "sco (Scots)"),
                            ("si", "si (Sinhala)"),
                            ("sk", "sk (Slovak)"),
                            ("sl", "sl (Slovenian)"),
                            ("son", "son (Songhai)"),
                            ("sq", "sq (Albanian)"),
                            ("sr", "sr (Serbian)"),
                            ("sr-Cyrl", "sr-Cyrl (Serbian)"),
                            ("sr-Latn", "sr-Latn (Serbian)"),
                            ("ss", "ss (Siswati)"),
                            ("st", "st (Southern Sotho)"),
                            ("sv-SE", "sv-SE (Swedish)"),
                            ("sw", "sw (Swahili)"),
                            ("szl", "szl (Silesian)"),
                            ("ta", "ta (Tamil)"),
                            ("ta-IN", "ta-IN (Tamil (India))"),
                            ("ta-LK", "ta-LK (Tamil (Sri Lanka))"),
                            ("te", "te (Telugu)"),
                            ("tg", "tg (Tajik)"),
                            ("th", "th (Thai)"),
                            ("tl", "tl (Tagalog)"),
                            ("tn", "tn (Tswana)"),
                            ("tr", "tr (Turkish)"),
                            ("trs", "trs (Triqui)"),
                            ("ts", "ts (Tsonga)"),
                            ("tsz", "tsz (Purépecha)"),
                            ("tt-RU", "tt-RU (Tatar)"),
                            ("uk", "uk (Ukrainian)"),
                            ("ur", "ur (Urdu)"),
                            ("uz", "uz (Uzbek)"),
                            ("ve", "ve (Venda)"),
                            ("vi", "vi (Vietnamese)"),
                            ("wo", "wo (Wolof)"),
                            ("x-testing", "x-testing (Testing)"),
                            ("xh", "xh (Xhosa)"),
                            ("yo", "yo (Yoruba)"),
                            ("zh-CN", "zh-CN (Chinese (Simplified))"),
                            ("zh-TW", "zh-TW (Chinese (Traditional))"),
                            ("zu", "zu (Zulu)"),
                        ],
                        default="en-US",
                        max_length=32,
                    ),
                ),
                (
                    "private",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this email is private. Private emails are not allowed to be sent via the normal subscribe API.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Braze transactional email",
                "ordering": ["message_id"],
                "unique_together": {("message_id", "language")},
            },
        ),
    ]
