# Generated by Django 4.2.17 on 2025-01-14 23:41

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_squashed_0001_to_0032"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuser",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apiuser",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
