# Generated by Django 5.2.17 on 2026-09-21 21:46

import secrets

from django.db import migrations, models

import basket.news.models


def backfill_unique_hmac_secrets(apps, schema_editor):
    # AddField evaluates a callable default once and reuses that single value to
    # backfill every existing row, so every pre-existing APIUser would otherwise end up
    # with the *same* hmac_secret. Regenerate one per row instead. No print()/logger of
    # the generated values here -- keep them out of migration/deploy logs.
    APIUser = apps.get_model("news", "APIUser")
    for user in APIUser.objects.all():
        user.hmac_secret = secrets.token_hex(32)
        user.save(update_fields=["hmac_secret"])


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_apiuser_created_apiuser_last_accessed"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiuser",
            name="allowed_form_ids",
            field=models.JSONField(
                blank=True, default=list, help_text="Form intake `form_id` slugs this user may submit to. Empty list = unrestricted."
            ),
        ),
        migrations.AddField(
            model_name="apiuser",
            name="hmac_secret",
            field=models.CharField(
                blank=True,
                default=basket.news.models.get_hmac_secret,
                help_text="Signing secret for /api/v1/intake/ requests (X-Basket-Signature). Never sent over the wire.",
                max_length=64,
            ),
        ),
        migrations.RunPython(backfill_unique_hmac_secrets, migrations.RunPython.noop),
    ]
