# Generated by Django 5.2.17 on 2026-09-22 23:42

from django.db import migrations, models

import basket.news.models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_apiuser_allowed_form_ids_apiuser_hmac_secret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apiuser",
            name="hmac_secret",
            field=models.CharField(
                default=basket.news.models.get_hmac_secret,
                help_text="Signing secret for /api/v1/intake/ requests (X-Basket-Signature). Never sent over the wire.",
                max_length=64,
            ),
        ),
    ]
