# Generated by Django 2.2.17 on 2021-03-23 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0021_delete_localizedsmsmessage"),
    ]

    operations = [
        migrations.DeleteModel(name="TransactionalEmailMessage"),
    ]
