# Generated by Django 2.2.17 on 2021-04-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0023_newsletter_firefox_confirm"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="is_mofo",
            field=models.BooleanField(
                default=False,
                help_text="True if subscribing to this newsletter should mark someone as relevant to the Mozilla Foundation",
            ),
        ),
    ]
