# Generated by Django 3.2.19 on 2023-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0026_newsletter_is_waitlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="requires_double_optin",
            field=models.BooleanField(
                default=False, help_text="True if subscribing to this newsletter requires someone to respond to a confirming email."
            ),
        ),
    ]
