# Generated by Django 3.2.19 on 2023-05-25 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0028_django_jsonfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CommonVoiceUpdate",
        ),
    ]
