# Generated by Django 4.2.11 on 2024-03-21 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0029_delete_commonvoiceupdate"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="localestewards",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="localestewards",
            name="interest",
        ),
        migrations.DeleteModel(
            name="Interest",
        ),
        migrations.DeleteModel(
            name="LocaleStewards",
        ),
    ]
