# Generated by Django 4.2.13 on 2024-05-17 19:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0031_brazetxemailmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AcousticTxEmailMessage",
        ),
    ]
